env:
  browser: true
  es2022: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - "@vue/eslint-config-typescript"
  - prettier
parserOptions:
  ecmaVersion: 13
plugins:
  - vue
  - "@typescript-eslint"
rules: {}
