env:
  browser: true
  es2022: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  ecmaVersion: 13
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules: {}
