name: frontend ci

on:
  push:
  pull_request:
    paths:
      - ./**

defaults:
  run:
    shell: bash
    # working-directory: frontend

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint and Build
        run: |-
          yarn install
          yarn fix
          yarn build
